from __future__ import annotations


PART2_CURRENT_CLASSES = [
    (1, 0, "Data"),
    (3, 0, "Register"),
    (4, 0, "Extended register"),
    (5, 0, "Demand register"),
    (6, 0, "Register activation"),
    (7, 1, "Profile generic"),
    (26, 0, "Utility tables"),
    (61, 0, "Register table"),
    (63, 0, "Status mapping"),
    (62, 1, "Compact data"),
    (66, 0, "Measurement data monitoring objects"),
    (12, 4, "Association SN"),
    (15, 3, "Association LN"),
    (17, 0, "SAP assignment"),
    (18, 0, "Image transfer"),
    (64, 1, "Security setup"),
    (30, 0, "COSEM data protection"),
    (123, 0, "Array manager"),
    (124, 0, "Communication port protection"),
    (8, 0, "Clock"),
    (9, 0, "Script table"),
    (10, 0, "Schedule"),
    (11, 0, "Special days table"),
    (20, 0, "Activity calendar"),
    (21, 0, "Register monitor"),
    (22, 0, "Single action schedule"),
    (70, 1, "Disconnect control"),
    (71, 0, "Limiter"),
    (65, 1, "Parameter monitor"),
    (67, 0, "Sensor manager"),
    (68, 0, "Arbitrator"),
    (111, 0, "Account"),
    (112, 0, "Credit"),
    (113, 0, "Charge"),
    (115, 0, "Token gateway"),
    (116, 0, "IEC 62055-41 attributes"),
    (19, 1, "IEC local port setup"),
    (23, 1, "IEC HDLC setup"),
    (24, 1, "IEC twisted pair (1) setup"),
    (27, 1, "Modem configuration"),
    (28, 2, "Auto answer"),
    (29, 2, "Auto connect"),
    (45, 0, "GPRS modem setup"),
    (25, 0, "M-Bus slave port setup"),
    (72, 2, "M-Bus client"),
    (73, 1, "Wireless Mode Q channel"),
    (74, 0, "M-Bus master port setup"),
    (76, 0, "DLMS server M-Bus port setup"),
    (77, 0, "M-Bus diagnostic"),
    (40, 3, "Push setup"),
    (41, 0, "TCP-UDP setup"),
    (42, 0, "IPv4 setup"),
    (48, 0, "IPv6 setup"),
    (43, 0, "MAC address setup"),
    (44, 0, "PPP setup"),
    (46, 0, "SMTP setup"),
    (100, 0, "NTP setup"),
    (153, 0, "CoAP diagnostic"),
    (50, 1, "S-FSK Phy&MAC set-up"),
    (51, 0, "S-FSK Active initiator"),
    (52, 0, "S-FSK MAC synchronization timeouts"),
    (53, 0, "S-FSK MAC counters"),
    (55, 1, "IEC 61334-4-32 LLC setup"),
    (56, 0, "S-FSK Reporting system list"),
    (57, 0, "ISO/IEC 8802-2 LLC Type 1 setup"),
    (58, 0, "ISO/IEC 8802-2 LLC Type 2 setup"),
    (59, 0, "ISO/IEC 8802-2 LLC Type 3 setup"),
    (80, 0, "61334-4-32 LLC SSCS setup"),
    (82, 0, "PRIME NB OFDM PLC MAC setup"),
    (84, 0, "PRIME NB OFDM PLC MAC counters"),
    (90, 1, "G3-PLC MAC layer counters"),
    (91, 4, "G3-PLC MAC setup"),
    (92, 4, "G3-PLC 6LoWPAN adaptation layer setup"),
    (160, 0, "G3-PLC Hybrid RF MAC layer counters"),
    (161, 1, "G3-PLC Hybrid RF MAC setup"),
    (140, 0, "HS-PLC ISO/IEC 12139-1 MAC setup"),
    (141, 0, "HS-PLC ISO/IEC 12139-1 CPAS setup"),
    (142, 0, "HS-PLC ISO/IEC 12139-1 IP SSAS setup"),
    (101, 0, "ZigBee SAS startup"),
    (102, 0, "ZigBee SAS join"),
    (103, 0, "ZigBee SAS APS fragmentation"),
    (104, 0, "ZigBee network control"),
    (105, 0, "ZigBee tunnel setup"),
    (130, 0, "ISO/IEC 14908 identification"),
    (131, 0, "ISO/IEC 14908 protocol setup"),
    (132, 0, "ISO/IEC 14908 protocol status"),
    (133, 0, "ISO/IEC 14908 diagnostic"),
    # 2026-06-27 补漏：Blue Book Part 2 Ed.16 Chapter 4 的 current 接口类，原 catalog 遗漏。
    # 经对照 Part 2 PDF（章节号 4.X.Y 确认为 current），主要为较新的蜂窝/PLC/Wi-SUN/LPWAN/
    # LoRaWAN 通信类；编译 KB 此前一并缺失这些类条目。
    (47, 2, "GSM diagnostic"),
    (81, 0, "PRIME NB OFDM PLC Physical layer counters"),
    (83, 0, "PRIME NB OFDM PLC MAC functional parameters"),
    (85, 0, "PRIME NB OFDM PLC MAC network administration data"),
    (86, 0, "PRIME NB OFDM PLC Application identification"),
    (95, 0, "Wi-SUN setup"),
    (96, 0, "Wi-SUN diagnostic"),
    (97, 0, "RPL diagnostic"),
    (98, 0, "MPL diagnostic"),
    (122, 0, "Function control"),
    (126, 0, "SCHC-LPWAN setup"),
    (127, 0, "SCHC-LPWAN diagnostic"),
    (128, 0, "LoRaWAN setup"),
    (129, 0, "LoRaWAN diagnostic"),
    (143, 0, "HS-PLC ISO/IEC 12139-1 HDLC SSAS setup"),
    (151, 1, "LTE monitoring"),
    (152, 0, "CoAP setup"),
    (162, 1, "G3-PLC Hybrid 6LoWPAN adaptation layer setup"),
]


PART1_OBIS_TABLES = [
    (1, "OBIS code structure and use of value groups"),
    (2, "Rules for manufacturer, utility, consortia and country specific codes"),
    (3, "Value group A codes"),
    (4, "Value group B codes"),
    (5, "Value group C codes - Abstract objects"),
    (6, "Value group D codes - Consortia specific identifiers"),
    (7, "Value group D codes - Country specific identifiers"),
    (8, "OBIS codes for general and service entry objects"),
    (9, "OBIS codes for error registers, alarm registers and alarm filters - Abstract"),
    (10, "OBIS codes for list objects - Abstract"),
    (11, "OBIS codes for Register table objects - Abstract"),
    (12, "OBIS codes for data profile objects - Abstract"),
    (13, "Value group C codes - AC Electricity"),
    (14, "Value group D codes - AC electricity"),
    (15, "Value group E codes - AC electricity - Tariff rates"),
    (16, "Value group E codes - AC electricity - Harmonics"),
    (17, "Value group E codes - AC electricity - Extended phase angle measurement"),
    (18, "Value group E codes - AC electricity - Transformer and line losses"),
    (19, "Value group E codes - AC electricity - UNIPEDE voltage dips"),
    (20, "Value group E codes for distortion power and energy"),
    (21, "OBIS codes for general and service entry objects - AC electricity"),
    (22, "OBIS codes for error register objects - AC electricity"),
    (23, "OBIS codes for list objects - AC electricity"),
    (24, "OBIS codes for data profile objects - AC electricity"),
    (25, "OBIS codes for register table objects - AC electricity"),
    (26, "Value group C codes - DC electricity"),
    (27, "Value group D codes - DC electricity"),
    (28, "Value group E codes - DC electricity - Tariff rates"),
    (29, "OBIS codes for general and service entry objects - DC electricity"),
    (30, "OBIS codes for error register objects - DC electricity"),
    (31, "OBIS codes for list objects - DC electricity"),
    (32, "OBIS codes for data profile objects - DC electricity"),
    (33, "OBIS codes for Register table objects - DC electricity"),
    (34, "Value group C codes - HCA"),
    (35, "Value group D codes - HCA"),
    (36, "Value group E codes - HCA"),
    (37, "OBIS codes for general and service entry objects - HCA"),
    (38, "OBIS codes for error register objects - HCA"),
    (39, "OBIS codes for list objects - HCA"),
    (40, "OBIS codes for data profile objects - HCA"),
    (41, "OBIS codes for HCA related objects (examples)"),
    (42, "Value group C codes - Thermal energy"),
    (43, "Value group D codes - Thermal energy"),
    (44, "Value group E codes - Thermal Energy - Tariff rates"),
    (45, "OBIS codes for general and service entry objects - Thermal energy"),
    (46, "OBIS codes for error register objects - Thermal energy"),
    (47, "OBIS codes for list objects - Thermal Energy Meters"),
    (48, "OBIS codes for data profile objects - Thermal energy"),
    (49, "OBIS codes for Thermal energy related objects (examples)"),
    (50, "OBIS codes of the main objects in the gas conversion process data flow"),
    (51, "Value group C codes - Gas"),
    (52, "Value group D codes - Gas - Indexes and index differences"),
    (53, "Value group D codes - Gas - Flow rate"),
    (54, "Value group D codes - Gas - Process values"),
    (55, "Value group D codes - Gas - Conversion related factors and coefficients"),
    (56, "Value group D codes - Gas - Natural gas analysis values"),
    (57, "Value group E codes - Gas - Indexes and index differences - Tariff rates"),
    (58, "Value group E codes - Gas - Conversion related factors and coefficients"),
    (59, "Value group E codes - Gas - Calculation methods"),
    (60, "Value group E codes - Gas - Natural gas analysis values - Averages"),
    (61, "OBIS codes for general and service entry objects - Gas"),
    (62, "OBIS codes for error register objects - Gas"),
    (63, "OBIS codes for list objects - Gas"),
    (64, "OBIS codes for data profile objects - Gas"),
    (65, "Value group C codes - Water"),
    (66, "Value group D codes - Water"),
    (67, "Value group E codes - Water"),
    (68, "OBIS codes for general and service entry objects - Water"),
    (69, "OBIS codes for error register objects - Water"),
    (70, "OBIS codes for list objects - Water Meters"),
    (71, "OBIS codes for data profile objects - Water"),
    (72, "OBIS codes for water related objects (examples)"),
    (73, "Value group C codes - Other media"),
]
