import type { DistributionItem, Requirement, SummaryCard, WorkflowStepStatus } from "./types"

export const workflowSteps = [
  { id: 1, title: "导入文档", subtitle: "已完成", status: "done" as WorkflowStepStatus },
  { id: 2, title: "抽取需求", subtitle: "已完成", status: "done" as WorkflowStepStatus },
  { id: 3, title: "AI 理解", subtitle: "已完成", status: "done" as WorkflowStepStatus },
  { id: 4, title: "人工审查", subtitle: "当前", status: "active" as WorkflowStepStatus },
  { id: 5, title: "装配规格", subtitle: "待开始", status: "pending" as WorkflowStepStatus },
  { id: 6, title: "导出", subtitle: "待开始", status: "pending" as WorkflowStepStatus },
]

export const navGroups = [
  { title: "", items: ["工作台", "审查工作区", "专家工作区", "装配规格", "术语/词库"] },
  { title: "文档中心", items: ["文档管理", "版本管理"] },
  { title: "数据与报表", items: ["审查统计", "质量分析"] },
  { title: "系统管理", items: ["用户管理", "权限管理", "设置中心"] },
]

export const summaryCards: SummaryCard[] = [
  { label: "总需求", value: 1248, delta: "较昨日 +42", tone: "blue" },
  { label: "待审查", value: 24, tone: "orange" },
  { label: "已审查", value: 984, delta: "79.0%", tone: "green" },
  { label: "待专家确认", value: 128, tone: "purple" },
  { label: "岐义需求", value: 36, tone: "red" },
]

export const confidenceDistribution: DistributionItem[] = [
  { label: "≥ 0.90", value: 42, percent: 32.8, tone: "green" },
  { label: "0.70 - 0.90", value: 63, percent: 49.2, tone: "blue" },
  { label: "< 0.70", value: 23, percent: 18.0, tone: "red" },
]

export const requirements: Requirement[] = [
  {
    id: "REQ-2024-0001",
    type: "功能",
    object: "用户",
    chineseText: "系统应支持用户通过手机号进行注册。",
    originalText: "The system shall support user registration through mobile number.",
    sourceDocument: "需求规格说明书_v2.1.docx",
    sourceLocation: "第 12 页 · 2.1.3",
    confidence: 0.96,
    risk: "低",
    status: "待审查",
    keyPoints: ["注册方式：手机号", "对象：用户", "动作：支持注册"],
    specMapping: { name: "USER_REGISTRATION_BY_PHONE", source: "账户服务规范 v1.3", matchRate: 0.93 },
    ambiguity: { level: "低", reasons: ["主体明确", "动作明确"] },
  },
  {
    id: "REQ-2024-0002",
    type: "性能",
    object: "查询服务",
    chineseText: "系统在并发用户数达到1000时，响应时间应不超过2秒。",
    originalText: "The response time shall not exceed 2 seconds when concurrent users reach 1000.",
    sourceDocument: "需求规格说明书_v2.1.docx",
    sourceLocation: "第 23 页 · 3.4.1",
    confidence: 0.82,
    risk: "中",
    status: "待审查",
    keyPoints: ["并发：1000", "响应时间：<=2秒"],
    ambiguity: { level: "中", reasons: ["压测条件未定义"] },
  },
  {
    id: "REQ-2024-0003",
    type: "安全",
    object: "数据传输",
    chineseText: "系统应对用户密码进行加密存储，算法为AES-256。",
    originalText: "User passwords shall be stored encrypted using AES-256.",
    sourceDocument: "需求规格说明书_v2.1.docx",
    sourceLocation: "第 24 页 · 3.4.2",
    confidence: 0.74,
    risk: "高",
    status: "待审查",
    keyPoints: ["密码加密", "算法：AES-256"],
    ambiguity: { level: "高", reasons: ["加密语义与哈希混用", "实现边界未明确"] },
  },
  {
    id: "REQ-2024-0004",
    type: "接口",
    object: "订单管理",
    chineseText: "系统应支持订单的创建、查询、取消和导出。",
    originalText: "The system shall support order creation, query, cancellation and export.",
    sourceDocument: "需求规格说明书_v2.1.docx",
    sourceLocation: "第 25 页 · 3.4.3",
    confidence: 0.93,
    risk: "低",
    status: "已接受",
    keyPoints: ["创建", "查询", "取消", "导出"],
    specMapping: { name: "ORDER_LIFECYCLE_MANAGEMENT", source: "订单平台规范 v4.0", matchRate: 0.88 },
    ambiguity: { level: "低", reasons: [] },
  },
  {
    id: "REQ-2024-0005",
    type: "环境",
    object: "运行环境",
    chineseText: "系统应兼容 Chrome、Edge、Firefox 最新两个版本。",
    originalText: "The system shall support the latest two versions of Chrome, Edge, and Firefox.",
    sourceDocument: "需求规格说明书_v2.1.docx",
    sourceLocation: "第 26 页 · 3.4.4",
    confidence: 0.88,
    risk: "低",
    status: "已接受",
    keyPoints: ["浏览器兼容性", "最新两个版本"],
    ambiguity: { level: "低", reasons: [] },
  },
  {
    id: "REQ-2024-0006",
    type: "功能",
    object: "订单管理",
    chineseText: "系统应支持订单的批量导入，文件格式为Excel。",
    originalText: "The system shall support batch import of orders in Excel format.",
    sourceDocument: "需求规格说明书_v2.1.docx",
    sourceLocation: "第 27 页 · 3.4.5",
    confidence: 0.68,
    risk: "中",
    status: "待审查",
    keyPoints: ["批量导入", "格式：Excel"],
    ambiguity: { level: "中", reasons: ["文件格式细节不足"] },
  },
  {
    id: "REQ-2024-0007",
    type: "性能",
    object: "接口",
    chineseText: "接口的吞吐量应不低于500 TPS。",
    originalText: "The interface throughput shall not be less than 500 TPS.",
    sourceDocument: "需求规格说明书_v2.1.docx",
    sourceLocation: "第 28 页 · 3.4.6",
    confidence: 0.77,
    risk: "中",
    status: "待专家确认",
    keyPoints: ["吞吐量：500 TPS"],
    ambiguity: { level: "中", reasons: ["测试条件未约束"] },
  },
  {
    id: "REQ-2024-0008",
    type: "安全",
    object: "系统",
    chineseText: "系统应在连续登录失败5次后锁定账号，锁定时间为30分钟。",
    originalText: "The account shall be locked for 30 minutes after five consecutive login failures.",
    sourceDocument: "需求规格说明书_v2.1.docx",
    sourceLocation: "第 29 页 · 3.4.7",
    confidence: 0.91,
    risk: "低",
    status: "已接受",
    keyPoints: ["失败次数：5", "锁定：30分钟"],
    ambiguity: { level: "低", reasons: [] },
  },
  {
    id: "REQ-2024-0009",
    type: "功能",
    object: "通知模块",
    chineseText: "系统应支持邮件和短信两种通知方式。",
    originalText: "The system shall support email and SMS notifications.",
    sourceDocument: "需求规格说明书_v2.1.docx",
    sourceLocation: "第 30 页 · 3.4.8",
    confidence: 0.6,
    risk: "高",
    status: "拒绝",
    keyPoints: ["邮件通知", "短信通知"],
    ambiguity: { level: "高", reasons: ["通知边界不明确", "渠道约束不足"] },
  },
  {
    id: "REQ-2024-0010",
    type: "数据",
    object: "用户",
    chineseText: "用户信息应包含姓名、手机号、邮箱、角色、状态等字段。",
    originalText: "User information shall include name, mobile number, email, role, and status.",
    sourceDocument: "需求规格说明书_v2.1.docx",
    sourceLocation: "第 31 页 · 3.4.9",
    confidence: 0.94,
    risk: "低",
    status: "已接受",
    keyPoints: ["字段清单明确"],
    ambiguity: { level: "低", reasons: [] },
  },
]
